import {Draw,P,PX} from './draw.js';
import {drawArt,drawEmblem,ART} from './art.js';
import {CRT} from './crt.js';
import {TerminalAudio} from './audio.js';

const display=document.querySelector('#display'),source=document.createElement('canvas');
source.width=640;source.height=360;
const ctx=source.getContext('2d',{alpha:false}),d=new Draw(ctx),audio=new TerminalAudio(),crt=new CRT(display,source);
const media=matchMedia('(prefers-reduced-motion: reduce)');
const defaults={brightness:.9,bloom:1,curvature:.3,persistence:.5,noise:.7,reducedMotion:media.matches,volume:.35,audio:true,phosphor:'flare-3'};
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const savedSettings=stored('call.settings',{});
const settings={...defaults,...savedSettings};
if(savedSettings.phosphor!=='flare-3'){settings.brightness=defaults.brightness;settings.bloom=defaults.bloom;settings.curvature=defaults.curvature;settings.persistence=defaults.persistence;settings.noise=defaults.noise;settings.phosphor='flare-3'}
audio.setEnabled(settings.audio);audio.setVolume(settings.volume);
const state={screen:'title',returnScreen:'title',catalog:null,monster:0,deck:0,custom:stored('call.deck',null),useCustom:false,page:0,school:'all',selected:null,inspect:null,handPage:0,choicePage:0,pending:null,view:null,snapshot:null,replay:null,result:null,history:[],busy:false,error:null,modal:null,hover:null,focus:null,pointer:null,fx:null,transition:performance.now(),fast:false,seed:861,continued:null,presentationError:null};
const journal=[];
let hits=[],controlsKey='',lastHover=null,lastDraw=0,clock=0,dirty=true;
const controls=document.querySelector('#controls'),announcement=document.querySelector('#announcement');
const schools={science:'科学',mystery:'神秘',religion:'宗教',neutral:'中立'};
const statuses={'status.mark':'解析','status.seal':'封印','status.protect':'保护','status.return':'返魂'};
const reasonNames={'full-board':'满格判定','resources':'资源结算','resource':'资源结算','special':'特殊结算','no-cards':'资源结算'};
const card=id=>state.catalog?.cards.find(c=>c.id===id)??state.catalog?.backs?.find(c=>c.id===id);
const name=id=>card(id)?.name??id??'';
const shortName=(s,max=4)=>[...s].length>max?[...s].slice(0,max).join('')+'·':s;
const options=()=>state.pending?.actor==='player'&&!state.busy?state.pending.options:[];
const invalidate=()=>{dirty=true};
function announce(s){announcement.textContent=s;}
function persistSettings(){try{localStorage.setItem('call.settings',JSON.stringify(settings))}catch{}audio.setEnabled(settings.audio);audio.setVolume(settings.volume);invalidate();}
function navigate(screen){state.screen=screen;state.modal=null;state.error=null;state.hover=null;state.focus=null;state.transition=performance.now();audio.play('select');invalidate();}
function hit(id,label,x,y,w,h,action,enabled=true,onHover=null){hits.push({id,label,x,y,w,h,action,enabled,onHover});}
function active(id){return state.hover===id||state.focus===id;}
function button(id,label,x,y,w,h,action,{enabled=true,selected=false,small=false}={}){const lit=active(id)||selected;d.rect(x,y,w,h,lit?2:0);d.box(x,y,w,h,enabled?(lit?4:2):1);if(lit)d.corners(x,y,w,h,5,4);if(small)d.small(label,x+7,y+Math.floor((h-7)/2),enabled?(lit?5:3):1);else d.text(label,x+9,y+Math.floor((h-12)/2)-1,enabled?(lit?5:4):2);hit(id,label,x,y,w,h,action,enabled);}
function rule(x,y,w,p=2){d.line(x,y,x+w,y,p)}
function header(section=''){if(section)d.text(section,20,14,3);rule(20,31,600,2)}
function waveform(x,y,w,h,time){for(let i=0;i<w;i+=PX){let yy=y+h/2+Math.sin(i*.15+time*.65)*(Math.sin(i*.021+time*.17)*.5+.5)*h*.34;d.rect(x+i,Math.round(yy/PX)*PX,PX,PX,2)}rule(x,y+h/2,w,1);}
function title(){
 rule(20,31,600,2);drawArt(ctx,'hero',16,44,288,252);
 d.text('THE CALL',332,52,5);
 button('receive','开始',332,96,268,32,()=>navigate('missions'));
 if(state.continued)button('continue','继续',332,140,268,28,()=>resume());
 button('archive','卡盒',332,208,128,28,()=>{state.returnScreen='title';navigate('archive')});button('calibrate','校准',472,208,128,28,()=>{state.returnScreen='title';state.modal='settings';invalidate()});
}
function missions(){
 header('关卡');
 state.catalog.monsters.forEach((m,i)=>{const x=20+i*203,lit=state.monster===i,nw=[...m.name].length*12;d.rect(x,44,194,140,0);d.box(x,44,194,140,lit?4:2);if(lit)d.corners(x,44,194,140,5,6);drawArt(ctx,m.id,x+73,96,ART,ART);d.text(m.name,x+Math.round((194-nw)/2),156,lit?5:3);hit('monster'+i,m.name,x,44,194,140,()=>{state.monster=i;audio.play('select');invalidate()});});
 d.text('牌组',20,208,3);
 state.catalog.decks.forEach((deck,i)=>button('deck'+i,deck.name,68+i*76,202,68,26,()=>{state.deck=i;state.useCustom=false;audio.play('select');invalidate()},{selected:!state.useCustom&&state.deck===i}));
 button('custom','自定义',296,202,80,26,()=>{if(state.custom&&validateDeck(state.custom).length===0){state.useCustom=true;invalidate()}else{state.returnScreen='missions';navigate('archive')}},{selected:state.useCustom});
 const deck=chosenDeck(),issues=validateDeck(deck),load=totalLoad(deck);
 d.text(deck.length+'/15',20,248,deck.length===15?2:5);d.text('负荷 '+load+'/90',92,248,load>90?5:2);
 const cap=issues.find(s=>s.includes('上限'));if(cap)d.text(cap,230,248,4);
 button('back','返回',20,292,72,26,()=>navigate('title'));
 button('edit','编辑',292,292,80,26,()=>{state.returnScreen='missions';navigate('archive')});
 button('start','开始',456,286,160,32,()=>start(),{enabled:!state.busy&&issues.length===0});
}
function chosenDeck(){return state.useCustom&&state.custom?state.custom:state.catalog.decks[state.deck].cards}
function totalLoad(deck){return (deck??[]).reduce((sum,id)=>sum+(card(id)?.load??0),0)}
function validateDeck(deck){const issues=[];if(deck.length!==15)issues.push('需要 15 张');if(totalLoad(deck)>90)issues.push('负荷超过 90');const counts={};for(const id of deck)counts[id]=(counts[id]??0)+1;for(const [id,n]of Object.entries(counts)){const c=card(id),cap=c?.rarity==='gold'?1:c?.rarity==='blue'?2:3;if(!c||n>cap)issues.push(name(id)+' 超出上限')}return issues}
function editDeck(id,delta){if(!state.custom)state.custom=[...state.catalog.decks[state.deck].cards];if(delta>0){const c=card(id),count=state.custom.filter(x=>x===id).length,cap=c.rarity==='gold'?1:c.rarity==='blue'?2:3;if(state.custom.length>=15||count>=cap){audio.play('error');state.error=state.custom.length>=15?'牌组已满':'已达同名上限';return}state.custom.push(id)}else{const i=state.custom.indexOf(id);if(i>=0)state.custom.splice(i,1)}try{localStorage.setItem('call.deck',JSON.stringify(state.custom))}catch{}state.error=null;audio.play(delta>0?'draw':'cancel');invalidate()}
function miniCard(c,x,y,w,h,id,action,amount=null){d.rect(x,y,w,h,0);d.box(x,y,w,h,active(id)?4:2);const nameY=y+h-16,ay=Math.max(y+12,nameY-ART-2);drawArt(ctx,c.id,x+Math.round((w-ART)/2),ay,ART,ART);d.small(c.isSpell?'S':String(c.points),x+4,y+4,c.isSpell?3:5);d.small('L'+c.load,x+w-18,y+4,2);d.text(c.name,x+4,nameY,4);if(amount!==null){d.rect(x+w-16,y+2,14,10,2);d.small('X'+amount,x+w-14,y+4,5)}hit(id,c.name,x,y,w,h,action,true,()=>{state.inspect=c.id;invalidate()});}
function archive(){
 header('卡盒');
 ['all','science','mystery','religion','neutral','backs'].forEach((school,i)=>button('school'+school,school==='all'?'全部':school==='backs'?'卡背':schools[school],20+i*65,41,60,22,()=>{state.school=school;state.page=0;invalidate()},{selected:state.school===school}));
 const cards=state.school==='backs'?state.catalog.backs:state.catalog.cards.filter(c=>c.id.startsWith('card.c')&&(state.school==='all'||c.school===state.school)),pages=Math.ceil(cards.length/10);state.page=Math.min(state.page,pages-1);
 cards.slice(state.page*10,state.page*10+10).forEach((c,i)=>{const x=20+(i%5)*79,y=73+Math.floor(i/5)*100;miniCard(c,x,y,73,92,'catalog'+c.id,()=>{state.inspect=c.id;state.modal={type:'card',id:c.id,edit:!c.isBack};invalidate()},c.isBack?null:(state.custom??[]).filter(id=>id===c.id).length)});
 button('prev','<',20,279,30,21,()=>{state.page--;invalidate()},{enabled:state.page>0,small:true});d.text((state.page+1)+'/'+pages,62,282,3);button('next','>',147,279,30,21,()=>{state.page++;invalidate()},{enabled:state.page<pages-1,small:true});
 d.box(430,41,188,260,2);d.text('牌组',441,49,4);rule(441,68,166);if(!state.custom)state.custom=[...state.catalog.decks[state.deck].cards];const entries=[...new Set(state.custom)],deckPages=Math.max(1,Math.ceil(entries.length/9));state.deckPage=Math.min(state.deckPage??0,deckPages-1);entries.slice(state.deckPage*9,state.deckPage*9+9).forEach((id,i)=>{d.text(shortName(name(id),8),441,77+i*16,3);d.small('X'+state.custom.filter(x=>x===id).length,568,80+i*16,3);button('remove'+id,'-',596,76+i*16,15,14,()=>editDeck(id,-1),{small:true})});if(deckPages>1){button('deckprev','<',441,229,22,18,()=>{state.deckPage--;invalidate()},{enabled:state.deckPage>0,small:true});d.text((state.deckPage+1)+'/'+deckPages,472,232,2);button('decknext','>',515,229,22,18,()=>{state.deckPage++;invalidate()},{enabled:state.deckPage<deckPages-1,small:true});}
 const valid=validateDeck(state.custom),load=totalLoad(state.custom);d.text(state.custom.length+'/15',441,256,state.custom.length===15?3:5);d.text('负荷 '+load+'/90',441,274,load>90?5:3);
 button('resetdeck','还原',20,308,72,22,()=>{state.custom=[...state.catalog.decks[state.deck].cards];state.error=null;try{localStorage.setItem('call.deck',JSON.stringify(state.custom))}catch{}invalidate()});
 button('archiveback','返回',292,308,80,22,()=>navigate(state.returnScreen));button('loaddeck','使用',430,308,188,22,()=>{state.useCustom=true;state.returnScreen='missions';navigate('missions')},{enabled:valid.length===0});
}
function boardRect(cell){const i=cell-1;return{x:172+i%3*90,y:40+Math.floor(i/3)*76,w:84,h:72}}
function cellOption(cell){const opts=options();if(state.pending?.type==='choose-cell')return opts.find(o=>o.cell===cell);if(state.pending?.type==='choose-card')return opts.find(o=>o.cell===cell&&o.kind==='card');if(state.selected!==null)return opts.find(o=>o.instance===state.selected&&o.cell===cell&&o.kind==='play');return opts.find(o=>o.cell===cell&&o.kind==='activate')}
function inspectCard(){return card(state.inspect)??card(state.view?.hand?.find(c=>c.instance===state.selected)?.cardId)}
function match(){
 const v=state.view;if(!v)return;
 header('回合 '+String(v.round).padStart(2,'0'));
 const m=state.catalog.monsters[state.monster];
 drawArt(ctx,m.id,20,42,ART,ART);d.text(String(v.monsterPoints).padStart(2,'0'),76,48,5);d.text(m.name,20,96,3);
 const intent=card(v.revealedIntent);
 if(intent){drawArt(ctx,intent.id,20,116,ART,ART);d.text('意图',76,120,2);d.text(shortName(intent.name,5),76,138,4);d.text(intent.isSpell?'法术':String(intent.points),76,156,3);hit('intent','查看意图 '+intent.name,20,116,148,52,()=>{state.modal={type:'card',id:intent.id};invalidate()},true,()=>{state.inspect=intent.id;invalidate()});}
 v.cells.forEach(cell=>{const r=boardRect(cell.cell),o=cellOption(cell.cell),c=cell.card,focus=active('cell'+cell.cell),flash=state.fx?.cell===cell.cell&&performance.now()-state.fx.at<240;d.rect(r.x,r.y,r.w,r.h,0);d.box(r.x,r.y,r.w,r.h,o?(focus?5:4):c?2:1);d.small(String(cell.cell),r.x+4,r.y+4,c?2:3);if(cell.polluted){d.hatch(r.x+r.w-8,r.y+28,6,16,2,4);d.small('!',r.x+r.w-10,r.y+4,4)}
  if(c){const marks=c.statuses??[];drawArt(ctx,c.cardId,r.x+2,r.y+2,ART,ART);d.small(String(c.currentPoints??0),r.x+54,r.y+4,marks.includes('status.seal')?2:5);d.text(name(c.cardId),r.x+4,r.y+56,3);if(c.owner==='monster'){d.rect(r.x+2,r.y+2,r.w-4,PX,2);d.small('M',r.x+70,r.y+4,3)}else d.rect(r.x+2,r.y+2,r.w-4,PX,3);marks.forEach((s,i)=>d.small(s==='status.mark'?'X':s==='status.protect'?'P':s==='status.return'?'R':'=',r.x+62,r.y+16+i*8,4));if(c.timer>0)d.small('T'+c.timer,r.x+62,r.y+16+marks.length*8,3);}
  else{d.line(r.x+34,r.y+36,r.x+48,r.y+36,1);d.line(r.x+40,r.y+28,r.x+40,r.y+44,1)}
  if(o)d.corners(r.x-1,r.y-1,r.w+2,r.h+2,focus?5:4,4);if(flash)d.corners(r.x+3,r.y+3,r.w-6,r.h-6,5,9);
  hit('cell'+cell.cell,(o?'确认格位 ':'查看格位 ')+cell.cell+(c?' '+name(c.cardId):''),r.x,r.y,r.w,r.h,()=>{if(o)answer(o.id);else if(c){state.inspect=c.cardId;state.modal={type:'card',id:c.cardId,instance:c};invalidate()}},!state.busy,()=>{if(c)state.inspect=c.cardId;invalidate()});
 });
 const seen=inspectCard();
 if(seen&&!state.modal){const h=seen.text?188:156;d.rect(456,42,168,h,0);d.box(456,42,168,h,active('inspect')?4:2);drawArt(ctx,seen.id,464,50,ART,ART);d.text(seen.name,520,50,4);d.text(seen.isSpell?'法术':seen.points+' 点',520,68,5);if(seen.text)d.wrap(seen.text,464,108,152,3,14,5);hit('inspect',seen.name,456,42,168,h,()=>{state.modal={type:'card',id:seen.id};invalidate()});}
 const hand=v.hand??[];state.handPage=Math.min(state.handPage,Math.max(0,Math.ceil(hand.length/7)-1));hand.slice(state.handPage*7,state.handPage*7+7).forEach((hc,i)=>{const def=card(hc.cardId);if(!def)return;const x=160+i*64,y=274-(state.selected===hc.instance?4:0),id='hand'+hc.instance,can=options().some(o=>o.instance===hc.instance&&(o.kind==='play'||o.kind==='cast')),selected=state.selected===hc.instance;d.rect(x,y,60,70,0);d.box(x,y,60,70,selected?5:can?3:1);drawArt(ctx,def.id,x+6,y+2,ART,ART);d.small(def.isSpell?'S':hc.currentPoints,x+40,y+4,can?5:2);d.small(String(i+1),x+4,y+4,2);d.text(shortName(def.name),x+4,y+54,can?4:2);if(selected)d.corners(x-2,y-2,64,74,5);hit(id,def.name,x,y,60,70,()=>selectHand(hc),can,()=>{state.inspect=hc.cardId;invalidate()});});
 if(hand.length>7){button('handprev','<',608,278,16,16,()=>{state.handPage=Math.max(0,state.handPage-1);invalidate()},{enabled:state.handPage>0,small:true});button('handnext','>',608,310,16,16,()=>{state.handPage++;invalidate()},{enabled:(state.handPage+1)*7<hand.length,small:true});}
 rule(16,176,140,1);d.text(String(v.playerPoints).padStart(2,'0'),20,184,5);d.text('库 '+v.matchDeckCount,20,204,2);d.text('手 '+v.handCount,78,204,2);
 const mine=(v.pools??[]).filter(p=>p.owner==='player').flatMap(p=>{const label=state.catalog.resources?.find(r=>r.id===p.id)?.name;return label?[label+' '+p.amount]:[]});
 let rail=226;if(mine.length){d.text(mine.join('  '),20,rail,3);rail+=18}
 button('piles','弃牌',20,rail,64,20,()=>{state.modal={type:'piles',page:0};invalidate()});
 const end=options().find(o=>o.kind==='end-turn');button('end','结束回合',20,rail+26,136,28,()=>answer(end.id),{enabled:!!end});
 if(state.pending?.type==='choose-card'&&!state.busy&&state.pending.options.some(o=>!o.cell)){hits=[];choices();}
}
function selectHand(hc){if(state.busy)return;state.inspect=hc.cardId;if(state.selected===hc.instance){state.selected=null;audio.play('cancel')}else {state.selected=hc.instance;audio.play('select');const cast=options().find(o=>o.instance===hc.instance&&o.kind==='cast');if(cast){state.modal={type:'cast',option:cast,id:hc.cardId}}}invalidate();}
function panel(x,y,w,h,title){d.rect(x,y,w,h,0);d.box(x,y,w,h,4);d.corners(x-2,y-2,w+4,h+4,3,6);d.text(title,x+12,y+8,4);rule(x+12,y+26,w-24,2);}
function choices(){panel(80,48,480,260,'选择目标');const opts=options(),pages=Math.max(1,Math.ceil(opts.length/8));opts.slice(state.choicePage*8,state.choicePage*8+8).forEach((o,i)=>{const c=card(o.cardId);if(!c)return;const x=96+i%4*115,y=78+Math.floor(i/4)*96;miniCard(c,x,y,108,90,'choice'+o.id,()=>answer(o.id));});if(pages>1){button('choiceprev','<',96,270,27,18,()=>{state.choicePage--;invalidate()},{enabled:state.choicePage>0,small:true});d.text((state.choicePage+1)+'/'+pages,136,274,3);button('choicenext','>',177,270,27,18,()=>{state.choicePage++;invalidate()},{enabled:state.choicePage<pages-1,small:true});}}
function cardModal(modal){const c=card(modal.id);if(!c){state.modal=null;return}panel(100,36,440,286,c.name);drawArt(ctx,c.id,118,68,ART,ART);const bits=[];if(c.isBack)bits.push('+'+c.points+' 点','负荷 '+c.load);else{bits.push(c.isSpell?'法术':((modal.instance?.currentPoints??c.points)+' 点'));if(schools[c.school])bits.push(schools[c.school]);if(modal.edit)bits.push('负荷 '+c.load)}if(modal.instance){const names=(modal.instance.statuses??[]).map(s=>statuses[s]).filter(Boolean);if(names.length)bits.push(names.join(' '));if(modal.instance.timer>0)bits.push('计时 '+modal.instance.timer)}bits.forEach((bit,i)=>d.text(bit,230,78+i*18,i?3:5));if(c.text)d.wrap(c.text,118,128,404,3,16,7);if(modal.edit){const amount=(state.custom??[]).filter(id=>id===c.id).length,cap=c.rarity==='gold'?1:c.rarity==='blue'?2:3;button('minus','卸下',118,282,88,26,()=>editDeck(c.id,-1),{enabled:amount>0});button('plus','装入',214,282,88,26,()=>editDeck(c.id,1),{enabled:(state.custom??[]).length<15&&amount<cap});d.text(String(amount),312,288,5)}button('cardclose','关闭',modal.edit?392:400,282,120,26,()=>{state.modal=null;invalidate()});}
function modal(){if(!state.modal)return;d.hatch(0,0,640,360,0,4);const m=state.modal;
 if(m.type==='card'){cardModal(m);return;}
 if(m.type==='cast'){panel(139,89,362,182,'施放');drawArt(ctx,m.id,154,118,ART,ART);d.text(name(m.id),214,118,5);d.wrap(card(m.id)?.text||'',214,142,270,3,15,4);button('castcancel','取消',154,228,98,28,()=>{state.modal=null;state.selected=null;invalidate()});button('castconfirm','施放',264,228,220,28,()=>{state.modal=null;answer(m.option.id)});return;}
 if(m==='settings'){panel(92,40,456,248,'校准');d.text('亮度',110,78,3);[.6,.9,1.2].forEach((v,i)=>button('bright'+i,['柔和','标准','明亮'][i],188+i*112,72,104,24,()=>{settings.brightness=v;persistSettings()},{selected:settings.brightness===v}));d.text('泛光',110,116,3);[.5,1,1.5].forEach((v,i)=>button('flare'+i,['内敛','磷光','过驱'][i],188+i*112,110,104,24,()=>{settings.bloom=v;persistSettings()},{selected:settings.bloom===v}));d.text('画面',110,154,3);button('motionfull','动态',188,148,160,24,()=>{settings.reducedMotion=false;persistSettings()},{selected:!settings.reducedMotion});button('motionreduced','静止',356,148,160,24,()=>{settings.reducedMotion=true;persistSettings()},{selected:settings.reducedMotion});d.text('音效',110,192,3);button('audioenabled',settings.audio?'开启':'静音',188,186,78,24,()=>{settings.audio=!settings.audio;persistSettings()});[.15,.35,.6].forEach((v,i)=>button('vol'+i,['低','中','高'][i],274+i*58,186,52,24,()=>{settings.volume=v;persistSettings()},{selected:settings.volume===v}));button('settingsclose','完成',392,246,132,26,()=>{state.modal=null;invalidate()});return;}
 if(m==='menu'){panel(172,78,296,206,'暂停');d.text('本机已保存',189,114,2);button('resume','返回对局',188,138,264,28,()=>{state.modal=null;invalidate()});button('menu-settings','校准',188,174,128,26,()=>{state.modal='settings';invalidate()});button('menu-help','手册',324,174,128,26,()=>{state.modal={type:'help',page:0};invalidate()});button('menu-trace','导出记录',188,208,264,26,()=>exportTrace());button('exit','回标题',188,242,264,26,()=>{saveMatch();navigate('title')});return;}
 if(m.type==='help'){panel(74,39,492,282,'手册');const pages=[['出牌','每回合抽 1 张，通常可出 1 张。','先选手牌，再选亮着的格子。','法术要先确认，再选目标。','可以盖过点数不超过自己的对方牌。','点数更高，扣掉对方点数。相同则一起离场。'],['胜负','满格后不立刻结束。下回合开始时，点数高的一方获胜。','牌库和手牌用尽也会结算。','解析 X，科学牌可以识别。','保护 P，挡一次普通移除，挡不住覆盖。','返魂 R，离场回到手牌。封印 =，不计入点数。','污染 !，落定后永久减 1。计时 T，回合开始倒数。'],['按键','Tab 切换，Enter 确认。','1 到 7 选手牌。选中后，1 到 9 落子。','E 结束回合。Esc 取消，或打开暂停。','空格加速。F1 手册。F8 导出记录。']];const lines=pages[m.page];d.text(lines[0],93,80,5);lines.slice(1).forEach((line,i)=>d.text(line,93,114+i*22,3));button('helpprev','<',93,282,35,23,()=>{m.page--;invalidate()},{enabled:m.page>0,small:true});d.text((m.page+1)+'/3',140,286,3);button('helpnext','>',178,282,35,23,()=>{m.page++;invalidate()},{enabled:m.page<2,small:true});button('helpclose','关闭',430,282,117,23,()=>{state.modal=null;invalidate()});return;}
 if(m.type==='piles'){panel(79,43,482,274,'弃牌');const v=state.view,list=[...v.playerDiscard,...v.monsterDiscard,...v.playerVoid,...v.monsterVoid];list.slice(m.page*8,m.page*8+8).forEach((c,i)=>{const def=card(c.cardId);if(!def)return;const x=95+i%4*114,y=78+Math.floor(i/4)*96;miniCard(def,x,y,108,90,'pile'+c.instance,()=>{state.modal={type:'card',id:c.cardId};invalidate()});d.rect(x+2,y+2,104,PX,c.owner==='player'?4:2);if(c.zone==='void')d.text('消',x+80,y+70,2)});if(list.length>8){button('pileprev','<',95,282,27,23,()=>{m.page--;invalidate()},{enabled:m.page>0,small:true});button('pilenext','>',135,282,27,23,()=>{m.page++;invalidate()},{enabled:(m.page+1)*8<list.length,small:true});}button('pileclose','关闭',423,282,120,23,()=>{state.modal=null;invalidate()});return;}
}
function result(){const r=state.result;if(!r)return;const win=r.winner==='player';panel(120,72,400,200,win?'胜利':'失败');d.text(String(r.playerPoints).padStart(2,'0'),200,118,5);d.text(String(r.monsterPoints).padStart(2,'0'),340,118,3);d.text('第 '+r.rounds+' 回合',200,168,3);d.text(reasonNames[r.reason]??'',200,190,2);button('replayexport','导出记录',144,224,120,28,()=>exportTrace());button('rematch','重开',272,224,88,28,()=>start());button('return','回关卡',368,224,128,28,()=>navigate('missions'));}
function errorBox(){if(!state.error)return;panel(104,117,432,125,'提示');d.wrap(state.error,120,153,399,3,15,3);button('trace','导出记录',120,205,128,25,()=>exportTrace());button('errorclose','确认',360,205,158,25,()=>{state.error=null;invalidate()});}
function syncControls(){const key=hits.filter(h=>h.enabled).map(h=>h.id+'|'+h.label).join(';');if(key===controlsKey)return;controlsKey=key;controls.replaceChildren();for(const h of hits.filter(h=>h.enabled)){const b=document.createElement('button');b.textContent=h.label;b.dataset.action=h.id;b.addEventListener('focus',()=>{state.focus=h.id;h.onHover?.();invalidate()});b.addEventListener('click',()=>activate(h.id));controls.append(b)}}
function render(){hits=[];d.rect(0,0,640,360,0);ctx.imageSmoothingEnabled=false;if(!state.catalog){if(state.error)d.wrap(state.error,80,150,480,3,16,4);else{d.text('装载中',302,156,4);waveform(174,190,292,28,clock)}return;}
 if(state.screen==='title')title();else if(state.screen==='missions')missions();else if(state.screen==='archive')archive();else match();
 if(state.screen==='match'&&state.result){hits=[];result();}
 if(state.modal){hits=[];modal();}if(state.error){hits=[];errorBox();}
 if(state.busy&&state.screen!=='match'){d.rect(0,0,640,360,0);d.text('连接中',302,156,4);waveform(174,190,292,28,clock);hits=[];}
 if(state.fx&&performance.now()-state.fx.at<380&&state.screen==='match'&&!state.modal){const f=state.fx;if(f.cell&&f.label){const r=boardRect(f.cell);d.rect(r.x+24,r.y+20,36,17,0);d.small(f.label,r.x+28,r.y+25,5)}}
 syncControls();}
function activate(id){const h=hits.find(h=>h.id===id);if(!h?.enabled)return;audio.unlock();audio.play('select');h.action();invalidate();}
function resize(){const rect=display.getBoundingClientRect(),scale=Math.max(1,Math.floor(rect.width*devicePixelRatio/640));display.width=640*scale;display.height=360*scale;invalidate();}
new ResizeObserver(resize).observe(display);
display.addEventListener('pointermove',e=>{state.pointer=crt.mapPoint(e.clientX,e.clientY);const {x,y}=state.pointer,h=[...hits].reverse().find(h=>x>=h.x&&x<h.x+h.w&&y>=h.y&&y<h.y+h.h);state.hover=h?.id??null;if(state.hover!==lastHover){lastHover=state.hover;if(h){h.onHover?.();if(h.enabled)audio.play('hover')}invalidate()}display.style.cursor=h?.enabled?'pointer':'crosshair';});
display.addEventListener('pointerleave',()=>{state.hover=null;invalidate()});
display.addEventListener('pointerdown',e=>{const {x,y}=crt.mapPoint(e.clientX,e.clientY),h=[...hits].reverse().find(h=>x>=h.x&&x<h.x+h.w&&y>=h.y&&y<h.y+h.h);if(h)activate(h.id);display.focus();});
document.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();state.fast=true;return}if(e.key==='F8'){e.preventDefault();exportTrace();return}if(e.key==='F1'&&!state.busy){e.preventDefault();state.modal={type:'help',page:0};invalidate();return}if(state.busy)return;if(e.key==='Escape'){e.preventDefault();if(state.error)state.error=null;else if(state.modal)state.modal=null;else if(state.selected!==null)state.selected=null;else if(state.screen==='match')state.modal='menu';else navigate(state.screen==='archive'?state.returnScreen:'title');audio.play('cancel');invalidate();return}if(state.modal)return;if(state.screen==='match'){if(e.key.toLowerCase()==='e'){const end=options().find(o=>o.kind==='end-turn');if(end)answer(end.id)}const n=Number(e.key);if(n>=1&&n<=9){e.preventDefault();audio.unlock();if(state.selected!==null||state.pending?.type==='choose-card'||state.pending?.type==='choose-cell'){const o=cellOption(n);if(o)answer(o.id)}else {const hc=state.view.hand[state.handPage*7+n-1];if(hc&&n<=7&&options().some(o=>o.instance===hc.instance))selectHand(hc)}}}});
document.addEventListener('keyup',e=>{if(e.key===' ')state.fast=false});
window.addEventListener('blur',()=>{state.fast=false});
async function toggleFullscreen(){const stage=document.querySelector('.stage');if(document.fullscreenElement)await document.exitFullscreen();else await stage.requestFullscreen();}
function delay(ms){return new Promise(resolve=>{if(settings.reducedMotion||state.fast||document.hidden){resolve();return}const begin=performance.now();let settled=false;const finish=()=>{if(settled)return;settled=true;resolve()};const backup=setTimeout(finish,ms+80);function tick(){if(settled)return;if(document.hidden||state.fast||performance.now()-begin>=ms){clearTimeout(backup);finish()}else requestAnimationFrame(tick)}requestAnimationFrame(tick)})}
function eventCaption(e){const n=name(e.card);switch(e.type){case 'card-entered':return n+'进入格'+e.cell;case 'card-played':return n+(e.cell?'发送至格'+e.cell:'施放法术');case 'points-changed':return n+' '+e.before+' → '+e.after;case 'card-removed':return n+'离场';case 'card-drawn':return '抽取 '+n;case 'intent-revealed':return '怪物意图：'+n;case 'turn-started':return e.owner==='player'?'玩家回合开始':'怪物回合开始';case 'status-changed':return n+(e.reason==='cleared'?'清除':'获得')+(statuses[e.source]??'状态');case 'cell-polluted':return '格'+e.cell+'受到污染';case 'resource-changed':return (e.owner==='player'?'玩家':'怪物')+'信仰 '+e.before+' → '+e.after;default:return ''}}
function projectedEvent(e){
 const v=state.view;if(!v?.cells)return;
 const board=v.cells.find(c=>c.card?.instance===e.instance),hc=v.hand?.find(c=>c.instance===e.instance);
 if(e.type==='card-entered'&&e.cell){const def=card(e.card),slot=v.cells[e.cell-1];if(def&&slot){slot.card={instance:e.instance,cardId:e.card,owner:e.owner,zone:'board',cell:e.cell,basePoints:def.points,currentPoints:e.points??def.points,isSpell:!!def.isSpell,statuses:[],timer:0};if(v.hand)v.hand=v.hand.filter(c=>c.instance!==e.instance);}}
 if(e.type==='card-removed'||e.type==='card-discarded'){if(board)board.card=null;if(v.hand)v.hand=v.hand.filter(c=>c.instance!==e.instance);}
 if(e.type==='points-changed'&&e.source!=='status.seal'){if(board?.card)board.card.currentPoints=e.after;if(hc)hc.currentPoints=e.after;}
 if(e.type==='status-changed'){const c=board?.card??hc;if(c){if(!Array.isArray(c.statuses))c.statuses=[];if(e.reason==='cleared')c.statuses=c.statuses.filter(s=>s!==e.source);else if(!c.statuses.includes(e.source))c.statuses.push(e.source);}}
 if(e.type==='cell-polluted'&&e.cell&&v.cells[e.cell-1])v.cells[e.cell-1].polluted=true;
 if(e.type==='resource-changed'){if(!Array.isArray(v.pools))v.pools=[];let pool=v.pools.find(p=>p.owner===e.owner&&p.id===e.source);if(pool)pool.amount=e.after;else v.pools.push({owner:e.owner,id:e.source,amount:e.after});}
 if(e.type==='card-played'&&v.hand)v.hand=v.hand.filter(c=>c.instance!==e.instance);
 if(e.type==='intent-revealed')v.revealedIntent=e.card;
 if(e.type==='turn-started'&&e.round)v.round=e.round;
 for(const owner of ['player','monster']){const cards=v.cells.map(c=>c.card).filter(c=>c?.owner===owner);v[owner+'Points']=cards.reduce((sum,c)=>sum+(Array.isArray(c.statuses)&&c.statuses.includes('status.seal')?0:(c.currentPoints||0)),0);v[owner+'Occupancy']=cards.length;}
}
function commit(response){state.view=response.view;state.pending=response.pending;state.snapshot=response.snapshot;state.replay=response.replay;state.hash=response.hash;state.result=response.result;state.fx=null;state.busy=false;if(response.result){try{audio.play(response.result.winner==='player'?'win':'lose')}catch{}state.continued=null;try{localStorage.removeItem('call.match')}catch{}}else saveMatch();announce(response.result?(response.result.winner==='player'?'胜利':'失败'):'回合 '+state.view.round+'，'+state.view.playerPoints+' 对 '+state.view.monsterPoints);invalidate();}
async function present(response){state.selected=null;state.inspect=null;state.modal=null;state.choicePage=0;state.result=null;try{for(const step of response.steps??[]){for(const e of step.events??[]){try{projectedEvent(e)}catch(err){state.presentationError=err.message}const caption=eventCaption(e);if(!caption)continue;state.history.push({seq:e.seq,text:caption});if(state.history.length>100)state.history.shift();const cell=e.cell??state.view?.cells?.find(c=>c.card?.instance===e.instance)?.cell;state.fx={at:performance.now(),cell,caption,label:e.type==='points-changed'&&e.after!=null&&e.before!=null?String(e.after-e.before):null};try{audio.play(e.type==='card-entered'?'enter':e.type==='points-changed'||e.type==='card-removed'?'damage':e.type==='card-drawn'?'draw':e.type==='intent-revealed'?'intent':e.type==='card-played'&&!e.cell?'spell':e.type==='turn-started'?'turn':'hover')}catch{}invalidate();await delay(e.type==='card-entered'||e.type==='points-changed'?150:e.type==='turn-started'?240:55)}if(step.view)state.view=step.view;invalidate();}}finally{commit(response)}}
async function request(path,body){let r;try{r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch{throw new Error('连接中断')}const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{throw new Error(r.ok?'响应无法读取':'请求失败（'+r.status+'）')}if(!r.ok)throw new Error(data?.error??('请求失败（'+r.status+'）'));return data}
async function start(){if(state.busy)return;await audio.unlock();audio.play('boot');state.busy=true;state.result=null;state.selected=null;state.inspect=null;state.view=null;state.history=[];state.presentationError=null;journal.length=0;invalidate();try{const response=await request('/api/start',{monsterId:state.catalog.monsters[state.monster].id,deckId:state.catalog.decks[state.deck].id,buildDeck:state.useCustom?state.custom:null,seed:state.seed});state.screen='match';state.view=structuredClone(response.steps[0].view);await present(response)}catch(e){state.busy=false;state.error=e.message;audio.play('error');invalidate()}}
function noteFailure(option,message){journal.push({option,message,round:state.view?.round??null,hash:state.hash??null});if(journal.length>40)journal.shift();}
async function answer(option){if(state.busy||!options().some(o=>o.id===option))return;await audio.unlock();state.busy=true;state.modal=null;invalidate();try{await present(await request('/api/answer',{snapshot:state.snapshot,option}))}catch(e){state.busy=false;noteFailure(option,e.message);state.error=e.message;audio.play('error');invalidate()}}
function saveMatch(){if(!state.snapshot||state.result)return;state.continued={snapshot:state.snapshot,view:state.view,pending:state.pending,replay:state.replay,hash:state.hash,monster:state.monster,deck:state.deck,useCustom:state.useCustom,contentHash:state.catalog.contentHash,journal:journal.slice(),presentationError:state.presentationError};try{localStorage.setItem('call.match',JSON.stringify(state.continued))}catch{}}
function resume(){const s=state.continued;if(!s)return;journal.length=0;if(Array.isArray(s.journal))journal.push(...s.journal);Object.assign(state,{snapshot:s.snapshot,view:s.view,pending:s.pending,replay:s.replay,hash:s.hash,monster:s.monster,deck:s.deck,useCustom:s.useCustom,presentationError:s.presentationError??null,selected:null,result:null,busy:false});navigate('match');}
function parseJson(value){if(value==null)return null;if(typeof value!=='string')return value;try{return JSON.parse(value)}catch{return value}}
let exporting=false;
async function exportTrace(){if(exporting)return;const shown=state.error;const live=state.snapshot||state.replay;const saved=!live&&state.continued?state.continued:null;const snapshot=parseJson(state.snapshot??saved?.snapshot??null);const replay=parseJson(state.replay??saved?.replay??null);if(!snapshot&&!replay){state.error='没有可导出的对局';audio.play('error');invalidate();return}const deck=state.useCustom?state.custom:state.catalog?.decks?.[state.deck]?.cards??null;const body={trace:1,seed:state.seed,monsterId:state.catalog?.monsters?.[saved?.monster??state.monster]?.id??null,deckId:state.useCustom?null:state.catalog?.decks?.[saved?.deck??state.deck]?.id??null,useCustom:!!(saved?saved.useCustom:state.useCustom),buildDeck:deck,contentHash:state.catalog?.contentHash??saved?.contentHash??null,hash:state.hash??saved?.hash??null,error:shown,presentationError:state.presentationError??saved?.presentationError??null,failures:(journal.length?journal:saved?.journal??[]).slice(),history:state.history,pending:state.pending??saved?.pending??null,view:state.view??saved?.view??null,result:state.result,screen:state.screen,replay,snapshot};exporting=true;try{const data=await request('/api/trace',body);state.error='已写到桌面：'+(data.file??'');audio.play('select');}catch(e){state.error='导出失败';audio.play('error');}finally{exporting=false;invalidate();}}
async function initialize(){try{await document.fonts.load('12px Terminal');const r=await fetch('/api/catalog');if(!r.ok)throw new Error('装载失败');state.catalog=await r.json();state.custom=Array.isArray(state.custom)&&state.custom.every(id=>card(id))?state.custom:[...state.catalog.decks[0].cards];const saved=stored('call.match',null);if(saved?.contentHash===state.catalog.contentHash&&saved.pending?.actor==='player')state.continued=saved;persistSettings();invalidate();announce('可以开始');}catch(e){state.error=e.message;invalidate()}}
function frame(t){clock=settings.reducedMotion?0:t/1000;try{if(dirty||(!settings.reducedMotion&&t-lastDraw>100)){render();dirty=false;lastDraw=t}}catch(err){dirty=false;lastDraw=t;state.presentationError=err.message}try{crt.render(t/1000,settings)}catch{}requestAnimationFrame(frame)}
requestAnimationFrame(frame);initialize();
// Read-only diagnostics: real visible state and framebuffer, never rules or hidden information.
window.terminal={inspect:()=>({screen:state.screen,busy:state.busy,pending:state.pending,view:state.view,result:state.result,modal:state.modal,error:state.error,controls:hits.map(({id,label,x,y,w,h,enabled})=>({id,label,x,y,w,h,enabled})),webgl:crt.supported}),framebuffer:()=>source.toDataURL('image/png'),toggleFullscreen};
