import {Draw,P} from './draw.js';
import {drawArt,drawEmblem} from './art.js';
import {CRT} from './crt.js';
import {TerminalAudio} from './audio.js';

const display=document.querySelector('#display'),source=document.createElement('canvas');
source.width=640;source.height=360;
const ctx=source.getContext('2d',{alpha:false}),d=new Draw(ctx),audio=new TerminalAudio(),crt=new CRT(display,source);
const media=matchMedia('(prefers-reduced-motion: reduce)');
const defaults={brightness:.8,bloom:.35,curvature:.25,persistence:.25,noise:.2,reducedMotion:media.matches,volume:.35,audio:true};
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const savedSettings=stored('call.settings',{}),settings={...defaults,...savedSettings};
audio.setEnabled(settings.audio);audio.setVolume(settings.volume);
const state={screen:'title',returnScreen:'title',catalog:null,monster:0,deck:0,custom:stored('call.deck',null),useCustom:false,page:0,school:'all',selected:null,inspect:null,handPage:0,choicePage:0,pending:null,view:null,snapshot:null,replay:null,result:null,history:[],busy:false,error:null,modal:null,hover:null,focus:null,pointer:null,fx:null,transition:performance.now(),fast:false,seed:861,continued:null};
let hits=[],controlsKey='',lastHover=null,lastDraw=0,clock=0,dirty=true;
const controls=document.querySelector('#controls'),announcement=document.querySelector('#announcement');
const descriptions=['工业区的旧型机械已脱离控制。识别解析标记，避免被连续炮击。','数据库仍在学习。倒计时装置与数据过量正在重写它的运算。','废燃区传来强烈的异常信号。污染格会侵蚀落定卡牌的点数。'];
const schools={science:'科学',mystery:'神秘',religion:'宗教',neutral:'中立'};
const statuses={'status.mark':'解析','status.seal':'封印','status.protect':'保护','status.return':'返魂'};
const reasonNames={'full-board':'满格判定','resources':'资源结算','resource':'资源结算','special':'特殊结算','no-cards':'资源结算'};
const card=id=>state.catalog?.cards.find(c=>c.id===id)??state.catalog?.backs?.find(c=>c.id===id);
const name=id=>card(id)?.name??id??'';
const shortName=(s,max=4)=>[...s].length>max?[...s].slice(0,max).join('')+'·':s;
const options=()=>state.pending?.actor==='player'&&!state.busy?state.pending.options:[];
const invalidate=()=>{dirty=true};
function announce(s){announcement.textContent=s;}
function persistSettings(){try{localStorage.setItem('call.settings',JSON.stringify(settings))}catch{}audio.setEnabled(settings.audio);audio.setVolume(settings.volume);document.querySelector('#sound-value').textContent=settings.audio?'ON':'OFF';invalidate();}
function navigate(screen){state.screen=screen;state.modal=null;state.error=null;state.hover=null;state.focus=null;state.transition=performance.now();audio.play('select');invalidate();}
function hit(id,label,x,y,w,h,action,enabled=true,onHover=null){hits.push({id,label,x,y,w,h,action,enabled,onHover});}
function active(id){return state.hover===id||state.focus===id;}
function button(id,label,x,y,w,h,action,{enabled=true,selected=false,small=false}={}){const lit=active(id)||selected;d.rect(x,y,w,h,lit?2:0);d.box(x,y,w,h,enabled?(lit?4:2):1);if(lit)d.corners(x,y,w,h,5,3);if(small)d.small(label,x+7,y+Math.floor((h-7)/2),enabled?(lit?5:3):1);else d.text(label,x+9,y+Math.floor((h-12)/2)-1,enabled?(lit?5:4):2);hit(id,label,x,y,w,h,action,enabled);}
function rule(x,y,w,p=2){d.line(x,y,x+w,y,p)}
function header(section,subtitle=''){d.small('THE CALL',20,17,4);d.small('/',79,17,2);d.small(section,92,17,3);if(subtitle)d.small(subtitle,345,17,2);rule(20,31,600,2);d.rect(613,16,5,5,4);}
function footer(text,right='A-09 / LINK ESTABLISHED'){rule(20,332,600,2);d.text(text,21,339,3);d.small(right,451,342,2)}
function technicalGrid(x,y,w,h){d.box(x,y,w,h,1);for(let xx=x+10;xx<x+w;xx+=20)for(let yy=y+10;yy<y+h;yy+=20)d.rect(xx,yy,1,1,1);d.corners(x,y,w,h,3,6)}
function waveform(x,y,w,h,time){for(let i=0;i<w;i++){let yy=y+h/2+Math.sin(i*.15+time*.65)*(Math.sin(i*.021+time*.17)*.5+.5)*h*.34;d.rect(x+i,Math.round(yy),1,1,2)}rule(x,y+h/2,w,1);for(let i=0;i<w;i+=20)d.line(x+i,y+h/2-2,x+i,y+h/2+2,3);}
function title(){
 header('RECEPTION SYSTEM','CARRIER 08.61 / STANDBY');
 technicalGrid(20,48,288,266);drawArt(ctx,'hero',21,55,286,248);
 d.small('SIGNAL DETECTED',332,53,3);d.small('THE',332,77,4,3);d.small('CALL',329,107,5,6,1);
 d.text('来自未知之地的呼唤',333,163,4);d.small('ASYMMETRIC CARD STRATEGY',333,182,2);
 button('receive','接收信号 / 开始对局',332,205,268,30,()=>navigate('missions'));
 if(state.continued)button('continue','继续未完成的对局',332,242,268,26,()=>resume());
 else{d.text('九个格位。一个预兆。你的回应。',333,247,3);waveform(334,266,264,21,clock)}
 button('archive','卡盒 / 图形档案',332,298,130,22,()=>{state.returnScreen='title';navigate('archive')});button('calibrate','终端校准',470,298,130,22,()=>{state.returnScreen='title';state.modal='settings';invalidate()});
 footer('选择一张牌，改变下一次呼唤。','P3 / 640 X 360 / REV. 86');
}
function missions(){
 header('CHANNEL SELECT','03 CONTACTS / PUBLIC INTENT');
 d.text('选择关卡',20,42,4);d.small('AVAILABLE CONTACTS',450,45,2);
 state.catalog.monsters.forEach((m,i)=>{const x=20+i*203,lit=state.monster===i;d.rect(x,61,194,157,0);d.box(x,61,194,157,lit?4:2);if(lit)d.corners(x,61,194,157,5,7);drawArt(ctx,m.id,x+44,66,105,105);d.small('0'+(i+1),x+9,71,lit?4:2);d.small('CONTACT',x+8,158,2);d.text(m.name,x+10,181,lit?5:3);d.small(i===0?'INDUSTRIAL / 05':i===1?'ARCHIVE / 08':'WASTELAND / 10',x+10,202,2);hit('monster'+i,'选择关卡 '+m.name,x,61,194,157,()=>{state.monster=i;audio.play('select');invalidate()});});
 d.wrap(descriptions[state.monster],23,225,570,3,15,2);
 d.text('装载牌组',20,263,3);
 state.catalog.decks.forEach((deck,i)=>button('deck'+i,deck.name,90+i*88,261,80,25,()=>{state.deck=i;state.useCustom=false;audio.play('select');invalidate()},{selected:!state.useCustom&&state.deck===i}));
 button('custom','自定义',354,261,84,25,()=>{if(state.custom&&validateDeck(state.custom).length===0){state.useCustom=true;invalidate()}else{state.returnScreen='missions';navigate('archive')}},{selected:state.useCustom});
 const deck=chosenDeck();d.small('15 RECORDS / LOAD '+totalLoad(deck)+'/90',23,301,2);
 button('back','返回',20,311,70,19,()=>navigate('title'));
 button('edit','编辑卡盒',330,297,100,29,()=>{state.returnScreen='missions';navigate('archive')});
 button('start','建立连接 >',445,292,169,34,()=>start(),{enabled:!state.busy&&validateDeck(deck).length===0});
 footer('怪物意图提前公开；落点由怪物自行决定。');
}
function chosenDeck(){return state.useCustom&&state.custom?state.custom:state.catalog.decks[state.deck].cards}
function totalLoad(deck){return (deck??[]).reduce((sum,id)=>sum+(card(id)?.load??0),0)}
function validateDeck(deck){const issues=[];if(deck.length!==15)issues.push('必须装载15张卡牌');if(totalLoad(deck)>90)issues.push('总负荷超过90');const counts={};for(const id of deck)counts[id]=(counts[id]??0)+1;for(const [id,n]of Object.entries(counts)){const c=card(id),cap=c?.rarity==='gold'?1:c?.rarity==='blue'?2:3;if(!c||n>cap)issues.push(name(id)+'超出同名上限')}return issues}
function editDeck(id,delta){if(!state.custom)state.custom=[...state.catalog.decks[state.deck].cards];if(delta>0){const c=card(id),count=state.custom.filter(x=>x===id).length,cap=c.rarity==='gold'?1:c.rarity==='blue'?2:3;if(state.custom.length>=15||count>=cap){audio.play('error');state.error=state.custom.length>=15?'牌组已满。先移除一张，再装载新卡牌。':'该卡牌已达到同名数量上限。';return}state.custom.push(id)}else{const i=state.custom.indexOf(id);if(i>=0)state.custom.splice(i,1)}try{localStorage.setItem('call.deck',JSON.stringify(state.custom))}catch{}state.error=null;audio.play(delta>0?'draw':'cancel');invalidate()}
function miniCard(c,x,y,w,h,id,action,amount=null){d.rect(x,y,w,h,0);d.box(x,y,w,h,active(id)?4:2);drawArt(ctx,c.id,x+4,y+13,w-8,h-34);d.small(c.isSpell?'S':String(c.points),x+5,y+4,c.isSpell?3:5);d.small('L'+c.load,x+w-20,y+4,2);d.text(c.name,x+4,y+h-19,4);if(amount!==null){d.rect(x+w-15,y+1,14,11,2);d.small('X'+amount,x+w-13,y+3,5)}hit(id,c.name,x,y,w,h,action,true,()=>{state.inspect=c.id;invalidate()});}
function archive(){
 header('GRAPHIC ARCHIVE',state.school==='backs'?'13 BACKS / READ-ONLY RECORDS':'51 RECORDS / DECK ASSEMBLY');
 ['all','science','mystery','religion','neutral','backs'].forEach((school,i)=>button('school'+school,school==='all'?'全部':school==='backs'?'卡背':schools[school],20+i*65,41,60,22,()=>{state.school=school;state.page=0;invalidate()},{selected:state.school===school}));
 const cards=state.school==='backs'?state.catalog.backs:state.catalog.cards.filter(c=>c.id.startsWith('card.c')&&(state.school==='all'||c.school===state.school)),pages=Math.ceil(cards.length/10);state.page=Math.min(state.page,pages-1);
 cards.slice(state.page*10,state.page*10+10).forEach((c,i)=>{const x=20+(i%5)*79,y=73+Math.floor(i/5)*100;miniCard(c,x,y,73,92,'catalog'+c.id,()=>{state.inspect=c.id;state.modal={type:'card',id:c.id,edit:!c.isBack};invalidate()},c.isBack?null:(state.custom??[]).filter(id=>id===c.id).length)});
 button('prev','<',20,279,30,21,()=>{state.page--;invalidate()},{enabled:state.page>0,small:true});d.small('PAGE '+(state.page+1)+'/'+pages,61,286,3);button('next','>',147,279,30,21,()=>{state.page++;invalidate()},{enabled:state.page<pages-1,small:true});
 d.box(430,41,188,260,2);d.text('构建牌组',441,49,4);rule(441,68,166);if(!state.custom)state.custom=[...state.catalog.decks[state.deck].cards];const entries=[...new Set(state.custom)],deckPages=Math.max(1,Math.ceil(entries.length/9));state.deckPage=Math.min(state.deckPage??0,deckPages-1);entries.slice(state.deckPage*9,state.deckPage*9+9).forEach((id,i)=>{d.text(shortName(name(id),8),441,77+i*16,3);d.small('X'+state.custom.filter(x=>x===id).length,568,80+i*16,3);button('remove'+id,'-',596,76+i*16,15,14,()=>editDeck(id,-1),{small:true})});if(deckPages>1){button('deckprev','<',441,229,22,18,()=>{state.deckPage--;invalidate()},{enabled:state.deckPage>0,small:true});d.small((state.deckPage+1)+'/'+deckPages,476,235,2);button('decknext','>',515,229,22,18,()=>{state.deckPage++;invalidate()},{enabled:state.deckPage<deckPages-1,small:true});}
 const valid=validateDeck(state.custom);d.small('RECORDS '+state.custom.length+'/15',441,258,state.custom.length===15?4:3);d.small('LOAD '+totalLoad(state.custom)+'/90',441,275,totalLoad(state.custom)>90?5:3);
 button('resetdeck','重置为当前预设',20,308,148,21,()=>{state.custom=[...state.catalog.decks[state.deck].cards];state.error=null;try{localStorage.setItem('call.deck',JSON.stringify(state.custom))}catch{}invalidate()});
 button('archiveback','返回',315,308,88,21,()=>navigate(state.returnScreen));button('loaddeck','装载自定义牌组',430,308,188,21,()=>{state.useCustom=true;state.returnScreen='missions';navigate('missions')},{enabled:valid.length===0});
 footer(state.school==='backs'?'卡背图形档案；当前内核未接通装备流程。':'点击卡牌查看完整记录；+ 装载，- 卸载。');
}
function boardRect(cell){const i=cell-1;return{x:173+i%3*89,y:63+Math.floor(i/3)*66,w:83,h:60}}
function cellOption(cell){const opts=options();if(state.pending?.type==='choose-cell')return opts.find(o=>o.cell===cell);if(state.pending?.type==='choose-card')return opts.find(o=>o.cell===cell&&o.kind==='card');if(state.selected!==null)return opts.find(o=>o.instance===state.selected&&o.cell===cell&&o.kind==='play');return opts.find(o=>o.cell===cell&&o.kind==='activate')}
function inspectCard(){return card(state.inspect)??card(state.view?.hand.find(c=>c.instance===state.selected)?.cardId)??card(state.view?.revealedIntent)}
function match(){
 const v=state.view;if(!v)return;
 header('TACTICAL MATRIX','ROUND '+String(v.round).padStart(2,'0')+' / '+(state.busy?'RESOLVING':state.pending?.type==='play'?'PLAYER TRANSMIT':'AWAITING RESPONSE'));
 const m=state.catalog.monsters[state.monster];d.small('CONTACT / '+String(state.monster+1).padStart(2,'0'),20,43,2);drawArt(ctx,m.id,20,55,135,122);d.text(m.name,21,181,4);
 rule(20,200,135);d.small('REVEALED INTENT',20,209,3);const intent=card(v.revealedIntent);
 if(intent){drawArt(ctx,intent.id,21,225,47,39);d.text(intent.name,74,227,4);d.small(intent.isSpell?'SPELL':'POWER '+intent.points,75,245,3);hit('intent','查看意图 '+intent.name,20,222,135,46,()=>{state.modal={type:'card',id:intent.id};invalidate()},true,()=>{state.inspect=intent.id;invalidate()});}
 d.text('玩家',175,42,3);d.small(String(v.playerPoints).padStart(2,'0'),204,39,5,2);d.small('VS',283,44,2);d.small(String(v.monsterPoints).padStart(2,'0'),369,39,4,2);d.text('怪物',403,42,3);
 v.cells.forEach(cell=>{const r=boardRect(cell.cell),o=cellOption(cell.cell),c=cell.card,focus=active('cell'+cell.cell),flash=state.fx?.cell===cell.cell&&performance.now()-state.fx.at<240;d.rect(r.x,r.y,r.w,r.h,0);d.box(r.x,r.y,r.w,r.h,o?(focus?5:4):c?2:1);d.small(String(cell.cell),r.x+4,r.y+4,c?2:3);if(cell.polluted){d.hatch(r.x+1,r.y+r.h-9,r.w-2,8,2,4);d.small('!',r.x+r.w-6,r.y+4,4)}
  if(c){drawArt(ctx,c.cardId,r.x+7,r.y+11,49,37);d.small(String(c.currentPoints),r.x+r.w-20,r.y+14,c.statuses.includes('status.seal')?2:5,2);d.text(name(c.cardId),r.x+5,r.y+r.h-15,3);if(c.owner==='monster'){d.hatch(r.x+1,r.y+1,r.w-2,3,3,3);d.small('M',r.x+68,r.y+3,3)}else{d.rect(r.x+1,r.y+1,r.w-2,2,3)}c.statuses.forEach((s,i)=>d.small(s==='status.mark'?'X':s==='status.protect'?'P':s==='status.return'?'R':'=',r.x+60+i*5,r.y+44,4));if(c.timer>0)d.small('T'+c.timer,r.x+59,r.y+35,3);}
  else {d.line(r.x+35,r.y+28,r.x+47,r.y+28,1);d.line(r.x+41,r.y+22,r.x+41,r.y+34,1);if(o)d.small('PLACE',r.x+27,r.y+45,3)}
  if(o)d.corners(r.x-1,r.y-1,r.w+2,r.h+2,focus?5:4,4);if(flash)d.corners(r.x+3,r.y+3,r.w-6,r.h-6,5,9);
  hit('cell'+cell.cell,(o?'确认格位 ':'查看格位 ')+cell.cell+(c?' '+name(c.cardId):''),r.x,r.y,r.w,r.h,()=>{if(o)answer(o.id);else if(c){state.inspect=c.cardId;state.modal={type:'card',id:c.cardId,instance:c};invalidate()}},!state.busy,()=>{if(c)state.inspect=c.cardId;invalidate()});
 });
 d.small('OCCUPANCY '+v.playerOccupancy+' / '+v.monsterOccupancy,175,261,2);d.small('9 CELLS / SHARED FIELD',304,261,2);
 d.box(453,41,165,226,2);const c=inspectCard();if(c){d.small('GRAPHIC RECORD',463,49,2);drawArt(ctx,c.id,465,64,139,83);d.text(c.name,464,153,5);d.small((c.isSpell?'SPELL':'UNIT / '+c.points)+'  LOAD '+c.load,465,171,3);d.wrap(c.text||'无附加能力。',464,185,144,3,15,4);d.small('CLICK TO EXPAND',464,251,2);hit('inspect','展开卡牌完整记录',453,41,165,226,()=>{state.modal={type:'card',id:c.id};invalidate()});}
 const hand=v.hand;state.handPage=Math.min(state.handPage,Math.max(0,Math.ceil(hand.length/7)-1));hand.slice(state.handPage*7,state.handPage*7+7).forEach((hc,i)=>{const x=173+i*62,y=277-(state.selected===hc.instance?5:0),def=card(hc.cardId),id='hand'+hc.instance,can=options().some(o=>o.instance===hc.instance&&(o.kind==='play'||o.kind==='cast')),selected=state.selected===hc.instance;d.rect(x,y,58,50,0);d.box(x,y,58,50,selected?5:can?3:1);drawArt(ctx,def.id,x+3,y+10,36,28);d.small(def.isSpell?'S':hc.currentPoints,x+44,y+14,can?5:2);d.small(String(i+1),x+4,y+3,2);d.text(shortName(def.name),x+3,y+37,can?4:2);if(selected)d.corners(x-1,y-1,60,52,5);hit(id,'选择手牌 '+def.name,x,y,58,50,()=>selectHand(hc),can,()=>{state.inspect=hc.cardId;invalidate()});});
 if(hand.length>7){button('handprev','<',605,278,15,16,()=>{state.handPage=Math.max(0,state.handPage-1);invalidate()},{enabled:state.handPage>0,small:true});button('handnext','>',605,310,15,16,()=>{state.handPage++;invalidate()},{enabled:(state.handPage+1)*7<hand.length,small:true});}
 const end=options().find(o=>o.kind==='end-turn');button('end','结束回合 >',20,277,135,27,()=>answer(end.id),{enabled:!!end});d.small('DECK '+v.matchDeckCount+' / HAND '+v.handCount,21,311,2);hit('piles','查看弃牌堆和消散区',20,308,135,19,()=>{state.modal={type:'piles',page:0};invalidate()});
 for(const pool of v.pools.filter(p=>p.owner==='player'))d.small('FAITH '+pool.amount,462,264,4);
 let prompt=state.busy?'信号处理中…':state.pending?.type==='choose-card'?'选择效果目标：亮框为合法选项。':state.pending?.type==='choose-cell'?'选择生成格位：亮框为合法选项。':state.selected!==null?'选择亮框格位，发送这张卡牌。':'选择手牌，或结束回合。';footer(prompt,'[ESC] MENU / [SPACE] FAST');
 if(state.pending?.type==='choose-card'&&!state.busy&&state.pending.options.some(o=>!o.cell)){hits=[];choices();}
}
function selectHand(hc){if(state.busy)return;state.inspect=hc.cardId;if(state.selected===hc.instance){state.selected=null;audio.play('cancel')}else {state.selected=hc.instance;audio.play('select');const cast=options().find(o=>o.instance===hc.instance&&o.kind==='cast');if(cast){state.modal={type:'cast',option:cast,id:hc.cardId}}}invalidate();}
function panel(x,y,w,h,title){d.rect(x,y,w,h,0);d.box(x,y,w,h,4);d.corners(x-2,y-2,w+4,h+4,3,6);d.small(title,x+12,y+11,4);rule(x+12,y+26,w-24,2);}
function choices(){panel(80,54,480,259,'DECISION / SELECT RECORD');d.text('请选择一张卡牌作为效果目标',96,87,4);const opts=options(),pages=Math.ceil(opts.length/8);opts.slice(state.choicePage*8,state.choicePage*8+8).forEach((o,i)=>{const c=card(o.cardId),x=96+i%4*115,y=109+Math.floor(i/4)*81;miniCard(c,x,y,103,74,'choice'+o.id,()=>answer(o.id));});button('choiceprev','<',96,284,27,18,()=>{state.choicePage--;invalidate()},{enabled:state.choicePage>0,small:true});d.small((state.choicePage+1)+'/'+pages,136,290,3);button('choicenext','>',177,284,27,18,()=>{state.choicePage++;invalidate()},{enabled:(state.choicePage+1)*8<opts.length,small:true});d.text('决策不可取消；候选项由内核给出。',230,285,2);}
function cardModal(modal){const c=card(modal.id);panel(113,43,414,275,'GRAPHIC RECORD / '+c.id.toUpperCase());drawArt(ctx,c.id,128,79,155,131);d.text(c.name,301,80,5,24);d.small(c.isBack?'CARD BACK / POWER +'+c.points:(c.isSpell?'SPELL':'UNIT / POWER '+(modal.instance?.currentPoints??c.points)),303,112,4);d.small('LOAD '+c.load+' / '+(c.isBack?'MODIFICATION':schools[c.school]??'MONSTER'),303,129,3);d.small(c.isBack?'CAP '+(c.cap||'UNLIMITED'):'COPIES '+(c.rarity==='gold'?1:c.rarity==='blue'?2:3),303,146,2);d.wrap(c.text||'无附加能力。',130,220,371,4,16,4);if(modal.instance){const info=modal.instance;d.text('状态：'+(info.statuses.map(s=>statuses[s]??s).join(' / ')||'无'),130,202,3)}if(c.isBack){d.text('只读档案',303,178,4);d.wrap('装备接口尚未接入。',303,198,203,2,15,2);}
 if(modal.edit){const amount=state.custom.filter(id=>id===c.id).length;button('minus','- 卸载',303,176,91,26,()=>editDeck(c.id,-1),{enabled:amount>0});button('plus','+ 装载',402,176,109,26,()=>editDeck(c.id,1),{enabled:state.custom.length<15&&amount<(c.rarity==='gold'?1:c.rarity==='blue'?2:3)});d.small('LOADED X'+amount,303,209,3);}
 button('cardclose','关闭记录',382,283,129,24,()=>{state.modal=null;invalidate()});}
function modal(){if(!state.modal)return;d.hatch(0,0,640,360,0,2);const m=state.modal;
 if(m.type==='card'){cardModal(m);return;}
 if(m.type==='cast'){panel(139,89,362,182,'SPELL / TRANSMIT CONFIRMATION');drawArt(ctx,m.id,154,125,100,82);d.text(name(m.id),273,130,5);d.wrap(card(m.id).text,273,152,206,3,15,4);button('castcancel','取消',154,228,98,28,()=>{state.modal=null;state.selected=null;invalidate()});button('castconfirm','施放法术 >',273,228,211,28,()=>{state.modal=null;answer(m.option.id)});return;}
 if(m==='settings'){panel(128,49,384,263,'TERMINAL CALIBRATION');d.text('显像校准',145,84,5);d.text('亮度',145,117,3);[.55,.8,1].forEach((v,i)=>button('bright'+i,['柔和','标准','明亮'][i],244+i*82,112,75,24,()=>{settings.brightness=v;persistSettings()},{selected:settings.brightness===v}));d.text('图像',145,154,3);button('motionfull','完整 CRT',244,148,117,25,()=>{settings.reducedMotion=false;persistSettings()},{selected:!settings.reducedMotion});button('motionreduced','静态舒适',370,148,117,25,()=>{settings.reducedMotion=true;persistSettings()},{selected:settings.reducedMotion});d.text('音效',145,191,3);button('audioenabled',settings.audio?'开启':'静音',244,185,75,25,()=>{settings.audio=!settings.audio;persistSettings()});[.15,.35,.6].forEach((v,i)=>button('vol'+i,['低','中','高'][i],329+i*53,185,47,25,()=>{settings.volume=v;persistSettings()},{selected:settings.volume===v}));d.wrap('静态舒适关闭余辉、信号漂移与环境运动。设置自动保存。',145,228,346,2,15,2);button('settingsclose','校准完成',360,273,128,25,()=>{state.modal=null;invalidate()});return;}
 if(m==='menu'){panel(172,78,296,209,'TRANSMISSION PAUSED');d.text('对局已保存在本机',189,115,3);button('resume','返回对局',188,143,264,29,()=>{state.modal=null;invalidate()});button('menu-settings','终端校准',188,179,128,27,()=>{state.modal='settings';invalidate()});button('menu-help','操作手册',324,179,128,27,()=>{state.modal={type:'help',page:0};invalidate()});button('exit','返回接收界面',188,214,264,28,()=>{saveMatch();navigate('title')});d.small('NO AUTOMATIC MOVES WHILE PAUSED',190,263,2);return;}
 if(m.type==='help'){panel(74,39,492,282,'A-09 / OPERATOR MANUAL');const pages=[['01 / 发送与占位','每回合抽1张牌，通常有1次出牌机会。','点击手牌，再点击亮框格位；法术先确认再选择目标。','亮框来自内核的合法选项，不是界面猜测。','占场卡可覆盖点数不高于自己的对方卡牌。','较高点数覆盖后扣除对方点数；相同则双方离场。','先看怪物公开意图，再决定是否占位、覆盖或保留。'],['02 / 胜负与词条','满格后并不立即结束：下一方回合开始时，总点数','更高的一方获胜。牌组与手牌耗尽时也会触发结算。','解析 X：可被科学类卡牌识别和利用。','保护 P：抵挡一次普通移除，无法抵挡覆盖。','返魂 R：离场返回手牌。封印 =：不计入总点数。','污染 !：打出落定后永久减1；计时 T：回合开始倒数。'],['03 / 键盘与设备','Tab / Shift+Tab：逐个选择可操作控件。','Enter：确认当前控件。1–7：选择可见手牌。','选定卡牌后，1–9：直接确认对应格位。','E：结束回合。Escape：取消选择或打开暂停菜单。','Space：加速当前演出。F1：操作手册。','声音仅在首次操作后启动；设备下方可静音、全屏。']];const lines=pages[m.page];d.text(lines[0],93,80,5);lines.slice(1).forEach((line,i)=>d.text(line,93,114+i*23,3));button('helpprev','<',93,282,35,23,()=>{m.page--;invalidate()},{enabled:m.page>0,small:true});d.small((m.page+1)+'/3',143,290,3);button('helpnext','>',178,282,35,23,()=>{m.page++;invalidate()},{enabled:m.page<2,small:true});button('helpclose','关闭手册',430,282,117,23,()=>{state.modal=null;invalidate()});return;}
 if(m.type==='piles'){panel(79,43,482,274,'DISCARD / VOID RECORDS');const v=state.view,list=[...v.playerDiscard,...v.monsterDiscard,...v.playerVoid,...v.monsterVoid];d.text('弃牌堆 / 消散区',95,82,4);if(!list.length)d.text('当前没有离场卡牌。',95,132,3);list.slice(m.page*8,m.page*8+8).forEach((c,i)=>{let x=95+i%4*114,y=109+Math.floor(i/4)*79;miniCard(card(c.cardId),x,y,103,72,'pile'+c.instance,()=>{state.modal={type:'card',id:c.cardId};invalidate()});d.small((c.owner==='player'?'P':'M')+' / '+(c.zone==='void'?'VOID':'DISC'),x+4,y+61,2)});button('pileprev','<',95,282,27,23,()=>{m.page--;invalidate()},{enabled:m.page>0,small:true});button('pilenext','>',135,282,27,23,()=>{m.page++;invalidate()},{enabled:(m.page+1)*8<list.length,small:true});button('pileclose','返回对局',423,282,120,23,()=>{state.modal=null;invalidate()});return;}
}
function result(){const r=state.result;if(!r)return;const win=r.winner==='player';panel(121,67,398,230,win?'CONTACT RESOLVED':'TRANSMISSION LOST');d.small(win?'VICTORY':'DEFEAT',145,110,win?5:3,4);d.text(win?'信号已解除 / 玩家胜利':'信号中断 / 怪物胜利',146,153,4);d.small('PLAYER '+r.playerPoints+' / MONSTER '+r.monsterPoints,146,181,3);d.text('第'+r.rounds+'回合 · '+(reasonNames[r.reason]??r.reason),146,200,3);button('replayexport','导出录像',145,236,100,27,()=>downloadReplay());button('rematch','再次连接',253,236,117,27,()=>start());button('return','返回关卡',378,236,120,27,()=>navigate('missions'));d.small('EVENT HASH '+(state.hash??'').slice(0,16),146,280,2);}
function errorBox(){if(!state.error)return;panel(104,117,432,125,'SYSTEM MESSAGE');d.wrap(state.error,120,153,399,4,15,3);button('errorclose','确认',413,205,105,25,()=>{state.error=null;invalidate()});}
function syncControls(){const key=hits.filter(h=>h.enabled).map(h=>h.id+'|'+h.label).join(';');if(key===controlsKey)return;controlsKey=key;controls.replaceChildren();for(const h of hits.filter(h=>h.enabled)){const b=document.createElement('button');b.textContent=h.label;b.dataset.action=h.id;b.addEventListener('focus',()=>{state.focus=h.id;h.onHover?.();invalidate()});b.addEventListener('click',()=>activate(h.id));controls.append(b)}}
function render(){hits=[];d.rect(0,0,640,360,0);ctx.imageSmoothingEnabled=false;if(!state.catalog){header('INITIALIZING');d.small('ESTABLISHING LINK',172,160,4,2);d.text(state.error??'正在装载规则内核与图形记录…',173,194,3);waveform(174,222,292,30,clock);return;}
 if(state.screen==='title')title();else if(state.screen==='missions')missions();else if(state.screen==='archive')archive();else match();
 if(state.screen==='match'&&state.result){hits=[];result();}
 if(state.modal){hits=[];modal();}if(state.error){hits=[];errorBox();}
 if(state.busy&&state.screen!=='match'){d.rect(0,0,640,360,0);panel(144,126,352,107,'ESTABLISHING CONTACT');d.text('正在装载牌组与怪物意图…',161,164,4);waveform(161,190,315,21,clock);hits=[];}
 if(state.fx&&performance.now()-state.fx.at<380&&state.screen==='match'&&!state.modal){const f=state.fx;if(f.cell&&f.label){const r=boardRect(f.cell);d.rect(r.x+24,r.y+20,36,17,0);d.small(f.label,r.x+28,r.y+25,5)}if(f.caption){d.rect(177,247,258,14,0);d.text(f.caption,180,247,4)}}
 syncControls();}
function activate(id){const h=hits.find(h=>h.id===id);if(!h?.enabled)return;audio.unlock();audio.play('select');h.action();invalidate();}
function resize(){const rect=display.getBoundingClientRect(),scale=Math.max(1,Math.floor(rect.width*devicePixelRatio/640));display.width=640*scale;display.height=360*scale;invalidate();}
new ResizeObserver(resize).observe(display);
display.addEventListener('pointermove',e=>{state.pointer=crt.mapPoint(e.clientX,e.clientY);const {x,y}=state.pointer,h=[...hits].reverse().find(h=>x>=h.x&&x<h.x+h.w&&y>=h.y&&y<h.y+h.h);state.hover=h?.id??null;if(state.hover!==lastHover){lastHover=state.hover;if(h){h.onHover?.();if(h.enabled)audio.play('hover')}invalidate()}display.style.cursor=h?.enabled?'pointer':'crosshair';});
display.addEventListener('pointerleave',()=>{state.hover=null;invalidate()});
display.addEventListener('pointerdown',e=>{const {x,y}=crt.mapPoint(e.clientX,e.clientY),h=[...hits].reverse().find(h=>x>=h.x&&x<h.x+h.w&&y>=h.y&&y<h.y+h.h);if(h)activate(h.id);display.focus();});
document.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();state.fast=true;return}if(e.key==='F1'&&!state.busy){e.preventDefault();state.modal={type:'help',page:0};invalidate();return}if(state.busy)return;if(e.key==='Escape'){e.preventDefault();if(state.error)state.error=null;else if(state.modal)state.modal=null;else if(state.selected!==null)state.selected=null;else if(state.screen==='match')state.modal='menu';else navigate(state.screen==='archive'?state.returnScreen:'title');audio.play('cancel');invalidate();return}if(state.modal)return;if(state.screen==='match'){if(e.key.toLowerCase()==='e'){const end=options().find(o=>o.kind==='end-turn');if(end)answer(end.id)}const n=Number(e.key);if(n>=1&&n<=9){e.preventDefault();audio.unlock();if(state.selected!==null||state.pending?.type==='choose-card'||state.pending?.type==='choose-cell'){const o=cellOption(n);if(o)answer(o.id)}else {const hc=state.view.hand[state.handPage*7+n-1];if(hc&&n<=7&&options().some(o=>o.instance===hc.instance))selectHand(hc)}}}});
document.addEventListener('keyup',e=>{if(e.key===' ')state.fast=false});
window.addEventListener('blur',()=>{state.fast=false});
document.querySelector('#sound').addEventListener('click',async()=>{await audio.unlock();settings.audio=!settings.audio;persistSettings()});
document.querySelector('#fullscreen').addEventListener('click',async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.equipment').requestFullscreen();});
function delay(ms){return new Promise(resolve=>{const begin=performance.now();function tick(){if(settings.reducedMotion||state.fast||performance.now()-begin>=ms)resolve();else requestAnimationFrame(tick)}tick()})}
function eventCaption(e){const n=name(e.card);switch(e.type){case 'card-entered':return n+'进入格'+e.cell;case 'card-played':return n+(e.cell?'发送至格'+e.cell:'施放法术');case 'points-changed':return n+' '+e.before+' → '+e.after;case 'card-removed':return n+'离场';case 'card-drawn':return '抽取 '+n;case 'intent-revealed':return '怪物意图：'+n;case 'turn-started':return e.owner==='player'?'玩家回合开始':'怪物回合开始';case 'status-changed':return n+(e.reason==='cleared'?'清除':'获得')+(statuses[e.source]??'状态');case 'cell-polluted':return '格'+e.cell+'受到污染';case 'resource-changed':return (e.owner==='player'?'玩家':'怪物')+'信仰 '+e.before+' → '+e.after;default:return ''}}
function projectedEvent(e){
 const v=state.view;if(!v)return;
 const board=v.cells.find(c=>c.card?.instance===e.instance),hc=v.hand.find(c=>c.instance===e.instance);
 if(e.type==='card-entered'&&e.cell){const def=card(e.card),c=v.cells[e.cell-1];c.card={instance:e.instance,cardId:e.card,owner:e.owner,zone:'board',cell:e.cell,basePoints:def.points,currentPoints:e.points??def.points,isSpell:def.isSpell,statuses:[],timer:0};v.hand=v.hand.filter(c=>c.instance!==e.instance);}
 if(e.type==='card-removed'||e.type==='card-discarded'){if(board)board.card=null;v.hand=v.hand.filter(c=>c.instance!==e.instance);}
 if(e.type==='points-changed'&&e.source!=='status.seal'){if(board)board.card.currentPoints=e.after;if(hc)hc.currentPoints=e.after;}
 if(e.type==='status-changed'){const c=board?.card??hc;if(c){if(e.reason==='cleared')c.statuses=c.statuses.filter(s=>s!==e.source);else if(!c.statuses.includes(e.source))c.statuses.push(e.source);}}
 if(e.type==='cell-polluted'&&e.cell)v.cells[e.cell-1].polluted=true;
 if(e.type==='resource-changed'){let pool=v.pools.find(p=>p.owner===e.owner&&p.id===e.source);if(pool)pool.amount=e.after;else v.pools.push({owner:e.owner,id:e.source,amount:e.after});}
 if(e.type==='card-played'){state.inspect=e.card;v.hand=v.hand.filter(c=>c.instance!==e.instance);}
 if(e.type==='intent-revealed')v.revealedIntent=e.card;
 if(e.type==='turn-started')v.round=e.round;
 for(const owner of ['player','monster']){const cards=v.cells.map(c=>c.card).filter(c=>c?.owner===owner);v[owner+'Points']=cards.reduce((sum,c)=>sum+(c.statuses.includes('status.seal')?0:c.currentPoints),0);v[owner+'Occupancy']=cards.length;}
}
async function present(response){state.selected=null;state.modal=null;state.choicePage=0;state.pending=null;state.result=null;for(const step of response.steps){for(const e of step.events){projectedEvent(e);const caption=eventCaption(e);if(caption){state.history.push({seq:e.seq,text:caption});if(state.history.length>100)state.history.shift();const cell=e.cell??state.view?.cells.find(c=>c.card?.instance===e.instance)?.cell;state.fx={at:performance.now(),cell,caption,label:e.type==='points-changed'?String(e.after-e.before):null};audio.play(e.type==='card-entered'?'enter':e.type==='points-changed'||e.type==='card-removed'?'damage':e.type==='card-drawn'?'draw':e.type==='intent-revealed'?'intent':e.type==='card-played'&&!e.cell?'spell':e.type==='turn-started'?'turn':'hover');invalidate();await delay(e.type==='card-entered'||e.type==='points-changed'?150:e.type==='turn-started'?240:55)}}state.view=step.view;invalidate();}
 state.view=response.view;state.pending=response.pending;state.snapshot=response.snapshot;state.replay=response.replay;state.hash=response.hash;state.result=response.result;state.fx=null;state.busy=false;if(response.result){audio.play(response.result.winner==='player'?'win':'lose');state.continued=null;try{localStorage.removeItem('call.match')}catch{}}else saveMatch();announce(response.result?(response.result.winner==='player'?'玩家胜利':'怪物胜利'):'第'+state.view.round+'回合，玩家'+state.view.playerPoints+'点，怪物'+state.view.monsterPoints+'点。'+(state.pending?.type==='play'?'请选择手牌':'请选择效果目标'));invalidate();}
async function request(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error??'内核请求失败（'+r.status+'）');return data}
async function start(){if(state.busy)return;await audio.unlock();audio.play('boot');state.busy=true;state.result=null;state.selected=null;state.inspect=null;state.view=null;state.history=[];invalidate();try{const response=await request('/api/start',{monsterId:state.catalog.monsters[state.monster].id,deckId:state.catalog.decks[state.deck].id,buildDeck:state.useCustom?state.custom:null,seed:state.seed});state.screen='match';state.view=structuredClone(response.steps[0].view);await present(response)}catch(e){state.busy=false;state.error=e.message;audio.play('error');invalidate()}}
async function answer(option){if(state.busy||!options().some(o=>o.id===option))return;await audio.unlock();state.busy=true;state.modal=null;invalidate();try{await present(await request('/api/answer',{snapshot:state.snapshot,option}))}catch(e){state.busy=false;state.error=e.message;audio.play('error');invalidate()}}
function saveMatch(){if(!state.snapshot||state.result)return;state.continued={snapshot:state.snapshot,view:state.view,pending:state.pending,replay:state.replay,hash:state.hash,monster:state.monster,deck:state.deck,useCustom:state.useCustom,contentHash:state.catalog.contentHash};try{localStorage.setItem('call.match',JSON.stringify(state.continued))}catch{}}
function resume(){const s=state.continued;if(!s)return;Object.assign(state,{snapshot:s.snapshot,view:s.view,pending:s.pending,replay:s.replay,hash:s.hash,monster:s.monster,deck:s.deck,useCustom:s.useCustom,selected:null,result:null,busy:false});navigate('match');}
function downloadReplay(){const blob=new Blob([state.replay],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='the-call-'+state.seed+'-'+state.hash.slice(0,12)+'.replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function initialize(){try{await document.fonts.load('12px Terminal');const r=await fetch('/api/catalog');if(!r.ok)throw new Error('内容目录装载失败');state.catalog=await r.json();state.custom=Array.isArray(state.custom)&&state.custom.every(id=>card(id))?state.custom:[...state.catalog.decks[0].cards];const saved=stored('call.match',null);if(saved?.contentHash===state.catalog.contentHash&&saved.pending?.actor==='player')state.continued=saved;persistSettings();invalidate();announce('终端就绪，接收信号开始游戏。')}catch(e){state.error=e.message;invalidate()}}
function frame(t){clock=settings.reducedMotion?0:t/1000;if(dirty||(!settings.reducedMotion&&t-lastDraw>100)){render();dirty=false;lastDraw=t}crt.render(t/1000,settings);requestAnimationFrame(frame)}
requestAnimationFrame(frame);initialize();
// Read-only diagnostics: real visible state and framebuffer, never rules or hidden information.
window.terminal={inspect:()=>({screen:state.screen,busy:state.busy,pending:state.pending,view:state.view,result:state.result,modal:state.modal,error:state.error,controls:hits.map(({id,label,x,y,w,h,enabled})=>({id,label,x,y,w,h,enabled})),webgl:crt.supported}),framebuffer:()=>source.toDataURL('image/png')};
