export class TerminalAudio {
 constructor(){this.enabled=true;this.volume=.35;this.context=null;}
 async unlock(){if(!this.context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;this.context=new Audio();this.master=this.context.createGain();this.master.gain.value=this.enabled?this.volume:0;this.master.connect(this.context.destination);this.noise=this.context.createBuffer(1,Math.floor(this.context.sampleRate*.4),this.context.sampleRate);const d=this.noise.getChannelData(0);let seed=0x861;for(let i=0;i<d.length;i++){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;d[i]=((seed>>>0)/4294967296)*2-1;}}
  if(this.context.state==='suspended')await this.context.resume();}
 setEnabled(value){this.enabled=value;if(this.master)this.master.gain.setTargetAtTime(value?this.volume:0,this.context.currentTime,.025);}
 setVolume(value){this.volume=value;if(this.master)this.master.gain.setTargetAtTime(this.enabled?value:0,this.context.currentTime,.025);}
 tone(freq,duration=.08,amplitude=.1,type='square',delay=0,end=null){if(!this.context||!this.enabled)return;const t=this.context.currentTime+delay,osc=this.context.createOscillator(),gain=this.context.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);if(end)osc.frequency.exponentialRampToValueAtTime(end,t+duration);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(amplitude,t+.004);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(this.master);osc.start(t);osc.stop(t+duration+.01);}
 clickNoise(duration=.06,amplitude=.09,frequency=1800){if(!this.context||!this.enabled)return;const t=this.context.currentTime,node=this.context.createBufferSource(),filter=this.context.createBiquadFilter(),gain=this.context.createGain();node.buffer=this.noise;filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.8;gain.gain.setValueAtTime(amplitude,t);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);node.connect(filter);filter.connect(gain);gain.connect(this.master);node.start(t);node.stop(t+duration);}
 play(name){switch(name){case 'hover':this.tone(980,.022,.025);break;case 'select':this.tone(740,.045,.075);this.tone(1480,.045,.05,'square',.045);break;case 'cancel':this.tone(470,.08,.06,'triangle',0,210);break;case 'boot':this.clickNoise(.16,.05,950);this.tone(82,.3,.12,'triangle',0,164);this.tone(660,.08,.06,'square',.26);this.tone(990,.1,.07,'square',.36);break;case 'enter':this.clickNoise(.07,.1,850);this.tone(150,.12,.16,'triangle',0,50);this.tone(840,.045,.06,'square',.04);break;case 'damage':this.clickNoise(.12,.18,1700);this.tone(110,.16,.12,'sawtooth',0,32);break;case 'draw':this.clickNoise(.035,.05,2200);this.tone(1240,.04,.03,'square',.03);break;case 'intent':this.tone(196,.13,.09,'triangle');this.tone(294,.14,.065,'triangle',.12);break;case 'turn':this.tone(330,.075,.07,'triangle');this.tone(440,.1,.06,'triangle',.08);break;case 'error':this.tone(130,.12,.08);this.tone(130,.1,.05,'square',.15);break;case 'win':[330,440,554,660,880].forEach((f,i)=>this.tone(f,.25,.08,'triangle',i*.11));break;case 'lose':[220,196,146,110].forEach((f,i)=>this.tone(f,.3,.09,'triangle',i*.16));break;case 'spell':this.tone(880,.2,.06,'triangle',0,1760);this.clickNoise(.15,.05,3000);break;}}
}
